#!/usr/bin/env python3
"""
HDAIS Fast Port Scanner TUI - Interactive Text User Interface
High-performance port scanning with async, masscan, and wide port range support
"""

import sys
import json
import time
import os
from datetime import datetime
from typing import List, Dict, Optional
from pathlib import Path

# Try to import rich for better TUI
try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Prompt, Confirm, IntPrompt
    from rich.table import Table
    from rich.progress import Progress, SpinnerColumn, BarColumn, TextColumn, TimeElapsedColumn
    from rich.live import Live
    from rich.layout import Layout
    from rich import box
    from rich.text import Text
    from rich.tree import Tree
    HAS_RICH = True
except ImportError:
    HAS_RICH = False
    print("Warning: 'rich' library not found. Install with: pip install rich")
    print("Falling back to basic interface...")

from hdais.scanners.port_scanner import GPUPortScanner, MasscanScanner


class PortScannerTUI:
    """Interactive TUI for Fast Port Scanner"""

    def __init__(self):
        self.console = Console() if HAS_RICH else None
        self.scanner_options = {
            'gpu_json': None,
            'confidence': 'HIGH',
            'mode': 'async',
            'ports': 'gpu',
            'timeout': 1.0,
            'threads': 10,
            'concurrent': 500,
            'output': None
        }
        self.scanner = None
        self.results = []

    def clear_screen(self):
        """Clear terminal screen"""
        if HAS_RICH:
            self.console.clear()
        else:
            print("\n" * 50)

    def show_banner(self):
        """Display application banner"""
        if HAS_RICH:
            banner = """
╔══════════════════════════════════════════════════════════════════════╗
║                                                                      ║
║       HDAIS Fast Port Scanner - Interactive TUI                     ║
║       Ultra-Fast Scanning with Async & Masscan Support              ║
║       Version 2.0.0                                                  ║
║                                                                      ║
╚══════════════════════════════════════════════════════════════════════╝
            """
            self.console.print(Panel(banner, style="bold cyan", box=box.DOUBLE))
        else:
            print("\n" + "="*70)
            print("   HDAIS Fast Port Scanner - Interactive TUI")
            print("   Ultra-Fast Scanning with Async & Masscan")
            print("="*70 + "\n")

    def main_menu(self) -> str:
        """Display main menu"""
        self.clear_screen()
        self.show_banner()

        if HAS_RICH:
            table = Table(title="Main Menu", box=box.ROUNDED, show_header=False)
            table.add_column("Option", style="cyan", no_wrap=True)
            table.add_column("Description", style="white")

            table.add_row("1", "Select GPU Report File")
            table.add_row("2", "Configure Scanner Mode (async/masscan/thread)")
            table.add_row("3", "Configure Port Range (gpu/common/top1000/all/custom)")
            table.add_row("4", "Advanced Settings")
            table.add_row("5", "View Current Configuration")
            table.add_row("6", "🚀 Start Port Scan")
            table.add_row("7", "Exit")

            self.console.print(table)

            choice = Prompt.ask("\nSelect option", choices=["1", "2", "3", "4", "5", "6", "7"], default="6")
        else:
            print("\nMain Menu:")
            print("1. Select GPU Report File")
            print("2. Configure Scanner Mode")
            print("3. Configure Port Range")
            print("4. Advanced Settings")
            print("5. View Current Configuration")
            print("6. Start Port Scan")
            print("7. Exit")
            choice = input("\nSelect option [1-7]: ").strip()

        return choice

    def select_gpu_report(self):
        """Select GPU report file"""
        self.clear_screen()
        self.show_banner()

        if HAS_RICH:
            self.console.print(Panel(
                "[cyan]Select GPU Cluster Report[/cyan]\n\n"
                "Enter the path to your GPU cluster analysis JSON file.\n"
                "This file is generated by the GPU analyzer (hdais-gpu).",
                title="GPU Report Selection",
                box=box.ROUNDED
            ))

        # List recent reports if available
        reports_dir = Path('./reports')
        if reports_dir.exists():
            gpu_reports = sorted(reports_dir.glob('gpu_cluster_analysis*.json'), key=os.path.getmtime, reverse=True)
            if gpu_reports and HAS_RICH:
                table = Table(title="Recent GPU Reports", box=box.SIMPLE)
                table.add_column("#", style="cyan")
                table.add_column("File", style="green")
                table.add_column("Modified", style="yellow")

                for i, report in enumerate(gpu_reports[:5], 1):
                    mtime = datetime.fromtimestamp(report.stat().st_mtime).strftime("%Y-%m-%d %H:%M")
                    table.add_row(str(i), report.name, mtime)

                self.console.print("\n")
                self.console.print(table)

        if HAS_RICH:
            file_path = Prompt.ask("\n[cyan]Enter GPU report path[/cyan]", default="")
        else:
            file_path = input("\nEnter GPU report path: ").strip()

        if file_path and Path(file_path).exists():
            self.scanner_options['gpu_json'] = file_path
            if HAS_RICH:
                self.console.print(f"\n[green]✓[/green] Selected: {file_path}")
                input("\nPress Enter to continue...")
        elif file_path:
            if HAS_RICH:
                self.console.print(f"\n[red]✗[/red] File not found: {file_path}")
            else:
                print(f"\n✗ File not found: {file_path}")
            input("\nPress Enter to continue...")

    def configure_scanner_mode(self):
        """Configure scanner mode"""
        self.clear_screen()
        self.show_banner()

        if HAS_RICH:
            self.console.print(Panel(
                "[cyan]Scanner Mode Configuration[/cyan]\n\n"
                "[bold green]async[/bold green] - Async I/O scanner (10-50x faster than threads, default)\n"
                "  • Best for most use cases\n"
                "  • Handles 500 concurrent connections\n"
                "  • No dependencies required\n\n"
                "[bold yellow]masscan[/bold yellow] - Ultra-fast masscan (100x+ faster)\n"
                "  • Requires masscan installed (apt-get install masscan)\n"
                "  • Best for scanning large port ranges\n"
                "  • May require root privileges\n\n"
                "[bold blue]thread[/bold blue] - Legacy thread-based scanner\n"
                "  • Slower but more compatible\n"
                "  • Use if async causes issues",
                title="Scanner Modes",
                box=box.ROUNDED
            ))

            # Check masscan availability
            masscan = MasscanScanner()
            if masscan.is_available():
                self.console.print("\n[green]✓[/green] Masscan is installed and available")
            else:
                self.console.print("\n[yellow]⚠[/yellow] Masscan not found (optional)")

            mode = Prompt.ask(
                "\n[cyan]Select scanner mode[/cyan]",
                choices=["async", "masscan", "thread"],
                default=self.scanner_options['mode']
            )
        else:
            print("\nScanner Modes:")
            print("1. async - Fast async I/O (default)")
            print("2. masscan - Ultra-fast (requires masscan)")
            print("3. thread - Legacy thread-based")
            choice = input("\nSelect mode [1-3]: ").strip()
            mode_map = {"1": "async", "2": "masscan", "3": "thread"}
            mode = mode_map.get(choice, "async")

        self.scanner_options['mode'] = mode

        if HAS_RICH:
            self.console.print(f"\n[green]✓[/green] Scanner mode set to: {mode}")
            input("\nPress Enter to continue...")

    def configure_port_range(self):
        """Configure port range"""
        self.clear_screen()
        self.show_banner()

        if HAS_RICH:
            table = Table(title="Port Range Options", box=box.ROUNDED)
            table.add_column("Option", style="cyan")
            table.add_column("Description", style="white")
            table.add_column("Ports", style="yellow")
            table.add_column("Speed", style="green")

            table.add_row("1", "GPU/HPC/ML focused ports", "~80", "⚡ Fast")
            table.add_row("2", "Common service ports", "~150", "⚡ Fast")
            table.add_row("3", "Top 1000 common ports", "1000", "⚡⚡ Medium")
            table.add_row("4", "All ports (full scan)", "65535", "⚡⚡⚡ Slow")
            table.add_row("5", "Custom port range", "varies", "varies")

            self.console.print(table)

            choice = Prompt.ask(
                "\n[cyan]Select port range[/cyan]",
                choices=["1", "2", "3", "4", "5"],
                default="1"
            )

            port_map = {
                "1": "gpu",
                "2": "common",
                "3": "top1000",
                "4": "all",
                "5": "custom"
            }

            port_range = port_map[choice]

            if port_range == "custom":
                self.console.print("\n[cyan]Custom Port Range Examples:[/cyan]")
                self.console.print("  • custom:1-1000          (ports 1 to 1000)")
                self.console.print("  • custom:80,443,8080     (specific ports)")
                self.console.print("  • custom:1-1000,8000-9000 (multiple ranges)")

                custom = Prompt.ask("\n[cyan]Enter custom range[/cyan]", default="1-1000")
                port_range = f"custom:{custom}"

            self.scanner_options['ports'] = port_range
            self.console.print(f"\n[green]✓[/green] Port range set to: {port_range}")
            input("\nPress Enter to continue...")
        else:
            print("\nPort Ranges:")
            print("1. GPU/HPC/ML ports (~80 ports)")
            print("2. Common ports (~150 ports)")
            print("3. Top 1000 ports")
            print("4. All ports (1-65535)")
            print("5. Custom range")
            choice = input("\nSelect range [1-5]: ").strip()

            port_map = {"1": "gpu", "2": "common", "3": "top1000", "4": "all"}
            if choice == "5":
                custom = input("Enter custom range (e.g., 1-1000): ").strip()
                self.scanner_options['ports'] = f"custom:{custom}"
            else:
                self.scanner_options['ports'] = port_map.get(choice, "gpu")

    def advanced_settings(self):
        """Configure advanced settings"""
        self.clear_screen()
        self.show_banner()

        if HAS_RICH:
            self.console.print(Panel(
                "[cyan]Advanced Scanner Settings[/cyan]",
                title="Advanced Configuration",
                box=box.ROUNDED
            ))

            # Confidence filter
            self.scanner_options['confidence'] = Prompt.ask(
                "\n[cyan]Minimum confidence level[/cyan]",
                choices=["HIGH", "MEDIUM", "LOW"],
                default=self.scanner_options['confidence']
            )

            # Timeout
            self.scanner_options['timeout'] = IntPrompt.ask(
                "[cyan]Connection timeout (seconds)[/cyan]",
                default=int(self.scanner_options['timeout'])
            )

            # Mode-specific settings
            if self.scanner_options['mode'] == 'async':
                self.scanner_options['concurrent'] = IntPrompt.ask(
                    "[cyan]Max concurrent connections[/cyan]",
                    default=self.scanner_options['concurrent']
                )
            elif self.scanner_options['mode'] == 'thread':
                self.scanner_options['threads'] = IntPrompt.ask(
                    "[cyan]Number of threads[/cyan]",
                    default=self.scanner_options['threads']
                )

            # Output file
            default_output = f"port_scan_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
            self.scanner_options['output'] = Prompt.ask(
                "[cyan]Output file name[/cyan]",
                default=default_output
            )

            self.console.print("\n[green]✓[/green] Advanced settings updated")
            input("\nPress Enter to continue...")

    def view_configuration(self):
        """Display current configuration"""
        self.clear_screen()
        self.show_banner()

        if HAS_RICH:
            table = Table(title="Current Configuration", box=box.ROUNDED)
            table.add_column("Setting", style="cyan", no_wrap=True)
            table.add_column("Value", style="green")

            table.add_row("GPU Report", self.scanner_options['gpu_json'] or "[red]Not set[/red]")
            table.add_row("Scanner Mode", self.scanner_options['mode'])
            table.add_row("Port Range", self.scanner_options['ports'])
            table.add_row("Confidence Filter", self.scanner_options['confidence'])
            table.add_row("Timeout", f"{self.scanner_options['timeout']}s")

            if self.scanner_options['mode'] == 'async':
                table.add_row("Max Concurrent", str(self.scanner_options['concurrent']))
            elif self.scanner_options['mode'] == 'thread':
                table.add_row("Threads", str(self.scanner_options['threads']))

            table.add_row("Output File", self.scanner_options['output'] or "[yellow]Auto-generated[/yellow]")

            self.console.print(table)
        else:
            print("\nCurrent Configuration:")
            print(f"  GPU Report: {self.scanner_options['gpu_json']}")
            print(f"  Scanner Mode: {self.scanner_options['mode']}")
            print(f"  Port Range: {self.scanner_options['ports']}")
            print(f"  Confidence: {self.scanner_options['confidence']}")
            print(f"  Timeout: {self.scanner_options['timeout']}s")

        input("\nPress Enter to continue...")

    def start_scan(self):
        """Start the port scan"""
        if not self.scanner_options['gpu_json']:
            if HAS_RICH:
                self.console.print("\n[red]✗[/red] Please select a GPU report file first!")
            else:
                print("\n✗ Please select a GPU report file first!")
            input("\nPress Enter to continue...")
            return

        self.clear_screen()
        self.show_banner()

        # Generate default output if not set
        if not self.scanner_options['output']:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            self.scanner_options['output'] = f"port_scan_{timestamp}.json"

        if HAS_RICH:
            self.console.print(Panel(
                f"[cyan]Starting Port Scan[/cyan]\n\n"
                f"GPU Report: {self.scanner_options['gpu_json']}\n"
                f"Scanner Mode: {self.scanner_options['mode']}\n"
                f"Port Range: {self.scanner_options['ports']}\n"
                f"Confidence: {self.scanner_options['confidence']}",
                title="Scan Configuration",
                box=box.ROUNDED
            ))

        # Initialize scanner
        try:
            self.scanner = GPUPortScanner(
                timeout=self.scanner_options['timeout'],
                threads=self.scanner_options['threads'],
                scanner_mode=self.scanner_options['mode'],
                port_range=self.scanner_options['ports'],
                max_concurrent=self.scanner_options['concurrent']
            )

            if HAS_RICH:
                self.console.print(f"\n[green]✓[/green] Scanner initialized with {len(self.scanner.ports)} ports")
                self.console.print(f"[green]✓[/green] Mode: {self.scanner.scanner_mode}")

            # Start scanning
            if HAS_RICH:
                with Progress(
                    SpinnerColumn(),
                    TextColumn("[progress.description]{task.description}"),
                    BarColumn(),
                    TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
                    TimeElapsedColumn(),
                    console=self.console
                ) as progress:
                    task = progress.add_task("[cyan]Scanning targets...", total=100)

                    # Perform scan
                    self.results = self.scanner.scan_from_gpu_report(
                        self.scanner_options['gpu_json'],
                        self.scanner_options['confidence']
                    )

                    progress.update(task, completed=100)
            else:
                print("\nScanning...")
                self.results = self.scanner.scan_from_gpu_report(
                    self.scanner_options['gpu_json'],
                    self.scanner_options['confidence']
                )

            # Generate report
            if self.results:
                self.scanner.generate_report(self.scanner_options['output'])

                # Display summary
                self.show_results_summary()
            else:
                if HAS_RICH:
                    self.console.print("\n[yellow]⚠[/yellow] No results found")
                else:
                    print("\n⚠ No results found")

        except Exception as e:
            if HAS_RICH:
                self.console.print(f"\n[red]✗ Error:[/red] {e}")
            else:
                print(f"\n✗ Error: {e}")

        input("\nPress Enter to continue...")

    def show_results_summary(self):
        """Display scan results summary"""
        if HAS_RICH:
            self.console.print("\n" + "="*70)
            self.console.print("[bold green]Scan Complete![/bold green]")
            self.console.print("="*70)

            # Summary statistics
            total_hosts = len(self.results)
            total_open_ports = sum(r.total_open_ports for r in self.results)
            hosts_with_risks = sum(1 for r in self.results if r.high_risk_services)
            total_risks = sum(len(r.high_risk_services) for r in self.results)

            summary_table = Table(title="Scan Summary", box=box.ROUNDED)
            summary_table.add_column("Metric", style="cyan")
            summary_table.add_column("Value", style="green", justify="right")

            summary_table.add_row("Hosts Scanned", str(total_hosts))
            summary_table.add_row("Total Open Ports", str(total_open_ports))
            summary_table.add_row("Hosts with High-Risk Services", str(hosts_with_risks))
            summary_table.add_row("Total High-Risk Services", str(total_risks))

            self.console.print("\n")
            self.console.print(summary_table)

            # Top findings
            if hosts_with_risks > 0:
                self.console.print("\n[bold yellow]⚠ High-Risk Hosts:[/bold yellow]")

                findings_table = Table(box=box.SIMPLE)
                findings_table.add_column("Host", style="cyan")
                findings_table.add_column("University", style="white")
                findings_table.add_column("Open Ports", style="yellow", justify="right")
                findings_table.add_column("High-Risk Services", style="red", justify="right")

                for result in sorted(self.results, key=lambda x: len(x.high_risk_services), reverse=True)[:10]:
                    if result.high_risk_services:
                        findings_table.add_row(
                            result.hostname,
                            result.university,
                            str(result.total_open_ports),
                            str(len(result.high_risk_services))
                        )

                self.console.print(findings_table)

            # Output files
            self.console.print(f"\n[green]✓[/green] JSON report: {self.scanner_options['output']}")
            markdown_file = self.scanner_options['output'].replace('.json', '_summary.md')
            self.console.print(f"[green]✓[/green] Markdown summary: {markdown_file}")

        else:
            print("\n" + "="*70)
            print("Scan Complete!")
            print("="*70)
            print(f"\nHosts Scanned: {len(self.results)}")
            print(f"Total Open Ports: {sum(r.total_open_ports for r in self.results)}")
            print(f"\nResults saved to: {self.scanner_options['output']}")

    def run(self):
        """Main TUI loop"""
        while True:
            choice = self.main_menu()

            if choice == "1":
                self.select_gpu_report()
            elif choice == "2":
                self.configure_scanner_mode()
            elif choice == "3":
                self.configure_port_range()
            elif choice == "4":
                self.advanced_settings()
            elif choice == "5":
                self.view_configuration()
            elif choice == "6":
                self.start_scan()
            elif choice == "7":
                if HAS_RICH:
                    self.console.print("\n[cyan]Thank you for using HDAIS Fast Port Scanner![/cyan]")
                else:
                    print("\nThank you for using HDAIS Fast Port Scanner!")
                break
            else:
                if HAS_RICH:
                    self.console.print("[red]Invalid choice. Please try again.[/red]")
                input("\nPress Enter to continue...")


def main():
    """Entry point for the TUI"""
    if not HAS_RICH:
        print("\nWarning: For the best experience, install the 'rich' library:")
        print("  pip install rich\n")

    try:
        tui = PortScannerTUI()
        tui.run()
    except KeyboardInterrupt:
        print("\n\nInterrupted by user. Exiting...")
        sys.exit(0)
    except Exception as e:
        print(f"\n\nError: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
